services:
  app:
    build: .
    container_name: artistify-app

    ports:
      - "8080:8080"

    depends_on:
      - postgres
      - redis

    env_file:
      - .env

    environment:
      DB_HOST: postgres
      DB_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:17
    container_name: artistify-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: targaryen
      POSTGRES_DB: musicdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: artistify-redis

    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"

volumes:
  postgres_data: