// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/mailing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailingServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverEmail string                 `protobuf:"bytes,1,opt,name=receiverEmail,proto3" json:"receiverEmail,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailingServiceRequest) Reset() {
	*x = MailingServiceRequest{}
	mi := &file_proto_mailing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailingServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailingServiceRequest) ProtoMessage() {}

func (x *MailingServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mailing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailingServiceRequest.ProtoReflect.Descriptor instead.
func (*MailingServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_mailing_proto_rawDescGZIP(), []int{0}
}

func (x *MailingServiceRequest) GetReceiverEmail() string {
	if x != nil {
		return x.ReceiverEmail
	}
	return ""
}

func (x *MailingServiceRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type MailingServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succes        bool                   `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailingServiceResponse) Reset() {
	*x = MailingServiceResponse{}
	mi := &file_proto_mailing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailingServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailingServiceResponse) ProtoMessage() {}

func (x *MailingServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mailing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailingServiceResponse.ProtoReflect.Descriptor instead.
func (*MailingServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_mailing_proto_rawDescGZIP(), []int{1}
}

func (x *MailingServiceResponse) GetSucces() bool {
	if x != nil {
		return x.Succes
	}
	return false
}

func (x *MailingServiceResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_mailing_proto protoreflect.FileDescriptor

const file_proto_mailing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/mailing.proto\x12\amailing\"O\n" +
	"\x15MailingServiceRequest\x12$\n" +
	"\rreceiverEmail\x18\x01 \x01(\tR\rreceiverEmail\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"L\n" +
	"\x16MailingServiceResponse\x12\x16\n" +
	"\x06succes\x18\x01 \x01(\bR\x06succes\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse2]\n" +
	"\x0eMailingService\x12K\n" +
	"\bSendMail\x12\x1e.mailing.MailingServiceRequest\x1a\x1f.mailing.MailingServiceResponseB\bZ\x06proto/b\x06proto3"

var (
	file_proto_mailing_proto_rawDescOnce sync.Once
	file_proto_mailing_proto_rawDescData []byte
)

func file_proto_mailing_proto_rawDescGZIP() []byte {
	file_proto_mailing_proto_rawDescOnce.Do(func() {
		file_proto_mailing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mailing_proto_rawDesc), len(file_proto_mailing_proto_rawDesc)))
	})
	return file_proto_mailing_proto_rawDescData
}

var file_proto_mailing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mailing_proto_goTypes = []any{
	(*MailingServiceRequest)(nil),  // 0: mailing.MailingServiceRequest
	(*MailingServiceResponse)(nil), // 1: mailing.MailingServiceResponse
}
var file_proto_mailing_proto_depIdxs = []int32{
	0, // 0: mailing.MailingService.SendMail:input_type -> mailing.MailingServiceRequest
	1, // 1: mailing.MailingService.SendMail:output_type -> mailing.MailingServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mailing_proto_init() }
func file_proto_mailing_proto_init() {
	if File_proto_mailing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mailing_proto_rawDesc), len(file_proto_mailing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mailing_proto_goTypes,
		DependencyIndexes: file_proto_mailing_proto_depIdxs,
		MessageInfos:      file_proto_mailing_proto_msgTypes,
	}.Build()
	File_proto_mailing_proto = out.File
	file_proto_mailing_proto_goTypes = nil
	file_proto_mailing_proto_depIdxs = nil
}
