global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "auth-service"

    metrics_path: /metrics

    static_configs:
      - targets:
          - "auth-service:8180"

  - job_name: "music-service"

    metrics_path: /metrics

    static_configs:
      - targets:
          - "music-service:8080"

  - job_name: "prometheus"

    static_configs:
      - targets:
          - "prometheus:9090"