// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsValidTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenString   string                 `protobuf:"bytes,1,opt,name=tokenString,proto3" json:"tokenString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsValidTokenRequest) Reset() {
	*x = IsValidTokenRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsValidTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsValidTokenRequest) ProtoMessage() {}

func (x *IsValidTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsValidTokenRequest.ProtoReflect.Descriptor instead.
func (*IsValidTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *IsValidTokenRequest) GetTokenString() string {
	if x != nil {
		return x.TokenString
	}
	return ""
}

type IsValidTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsValidTokenResponse) Reset() {
	*x = IsValidTokenResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsValidTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsValidTokenResponse) ProtoMessage() {}

func (x *IsValidTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsValidTokenResponse.ProtoReflect.Descriptor instead.
func (*IsValidTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *IsValidTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenString   string                 `protobuf:"bytes,1,opt,name=tokenString,proto3" json:"tokenString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleRequest) GetTokenString() string {
	if x != nil {
		return x.TokenString
	}
	return ""
}

type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type IsValidAndGetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenString   string                 `protobuf:"bytes,1,opt,name=tokenString,proto3" json:"tokenString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsValidAndGetRoleRequest) Reset() {
	*x = IsValidAndGetRoleRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsValidAndGetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsValidAndGetRoleRequest) ProtoMessage() {}

func (x *IsValidAndGetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsValidAndGetRoleRequest.ProtoReflect.Descriptor instead.
func (*IsValidAndGetRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *IsValidAndGetRoleRequest) GetTokenString() string {
	if x != nil {
		return x.TokenString
	}
	return ""
}

type IsValidAndGetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsValidAndGetRoleResponse) Reset() {
	*x = IsValidAndGetRoleResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsValidAndGetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsValidAndGetRoleResponse) ProtoMessage() {}

func (x *IsValidAndGetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsValidAndGetRoleResponse.ProtoReflect.Descriptor instead.
func (*IsValidAndGetRoleResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *IsValidAndGetRoleResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *IsValidAndGetRoleResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"7\n" +
	"\x13IsValidTokenRequest\x12 \n" +
	"\vtokenString\x18\x01 \x01(\tR\vtokenString\",\n" +
	"\x14IsValidTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"2\n" +
	"\x0eGetRoleRequest\x12 \n" +
	"\vtokenString\x18\x01 \x01(\tR\vtokenString\"%\n" +
	"\x0fGetRoleResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"<\n" +
	"\x18IsValidAndGetRoleRequest\x12 \n" +
	"\vtokenString\x18\x01 \x01(\tR\vtokenString\"E\n" +
	"\x19IsValidAndGetRoleResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role2\xea\x01\n" +
	"\x13AuthenticateService\x12E\n" +
	"\fIsValidToken\x12\x19.auth.IsValidTokenRequest\x1a\x1a.auth.IsValidTokenResponse\x126\n" +
	"\aGetRole\x12\x14.auth.GetRoleRequest\x1a\x15.auth.GetRoleResponse\x12T\n" +
	"\x11IsValidAndGetRole\x12\x1e.auth.IsValidAndGetRoleRequest\x1a\x1f.auth.IsValidAndGetRoleResponseB\bZ\x06proto/b\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_proto_goTypes = []any{
	(*IsValidTokenRequest)(nil),       // 0: auth.IsValidTokenRequest
	(*IsValidTokenResponse)(nil),      // 1: auth.IsValidTokenResponse
	(*GetRoleRequest)(nil),            // 2: auth.GetRoleRequest
	(*GetRoleResponse)(nil),           // 3: auth.GetRoleResponse
	(*IsValidAndGetRoleRequest)(nil),  // 4: auth.IsValidAndGetRoleRequest
	(*IsValidAndGetRoleResponse)(nil), // 5: auth.IsValidAndGetRoleResponse
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthenticateService.IsValidToken:input_type -> auth.IsValidTokenRequest
	2, // 1: auth.AuthenticateService.GetRole:input_type -> auth.GetRoleRequest
	4, // 2: auth.AuthenticateService.IsValidAndGetRole:input_type -> auth.IsValidAndGetRoleRequest
	1, // 3: auth.AuthenticateService.IsValidToken:output_type -> auth.IsValidTokenResponse
	3, // 4: auth.AuthenticateService.GetRole:output_type -> auth.GetRoleResponse
	5, // 5: auth.AuthenticateService.IsValidAndGetRole:output_type -> auth.IsValidAndGetRoleResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
