name: "Artistify CI"

on:
    push:
        branches:
               - main
        
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:17
                env:
                    POSTGRES_DB: musicdb
                    POSTGRES_PASSWORD: targaryen
                    POSTGRES_USER: postgres

                ports:
                    - 5432:5432

            redis:
                image: redis:8

                ports:
                    - 6379:6379

        steps:
            - name: Checkout
              uses: actions/checkout@4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: "1.25"

            - name: Install Dependencies
              run: go mod tidy

            - name: Format Check
              run: test -z "$(gofmt -l .)"

            - name: Go Vet test
              run: go vet ./...

            - name: Run Linter test
              run: golangci-lint run

            - name: Run Test
              run: go test ./...

            - name: Build Project
              run: go build ./...